# Binance Exchange Configuration
binance:
  symbol: 'BTC/USDT'                    # Trading pair to monitor

# Kraken Exchange Configuration
#kraken:
#  symbol: 'BTC/USD'                     # Trading pair to monitor

# Other exchanges can be added in a similar manner