# Binance Exchange Configuration
binance:
  exchange_class: 'BinanceFetcher'
  symbols:
    - 'BTC/USDT'
    - 'ETH/USDT'
    - 'LTC/USDT'

# Kraken Exchange Configuration
kraken:
  exchange_class: 'KrakenFetcher'
  symbols:
    - 'BTC/USDT'
    - 'ETH/USD'
    - 'LTC/USD'

# ExampleExchange Configuration
#example_exchange:
#  exchange_class: 'ExampleExchangeFetcher'
#  symbols:
#    - 'BTC/USDT'
#    - 'ETH/USDT'
#    - 'ADA/USDT'